# Generated by Django 4.2.18 on 2025-01-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_customuser_is_employee'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
