# Generated by Django 4.2.18 on 2025-02-03 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 7, 5, 6, 757242, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
